### ISSUE TITLE
pio train exits without error

### ISSUE THREAD

**Issue by badeleux** [actionml/universal-recommender#16]
Following quickstart [guide](http://www.actionml.com/docs/ur_quickstart) I stumbled across some trivial problem. 
Integration test doesn't work for me and it doesn't return any error whatsoever. I found that the problem is in model training

When trying to train recommender using command:

`pio train  -- --driver-memory 4g --executor-memory 4g`
    
it returns
```
[INFO] [Console$] Using existing engine manifest JSON at /root/ur/manifest.json
[INFO] [Runner$] Submission command: /PredictionIO-0.10.0-incubating/vendors/spark-1.5.1-bin-hadoop2.6/bin/spark-submit --driver-memory 4g --executor-memory 4g --class org.apache.predictionio.workflow.CreateWorkflow --jars file:/root/ur/target/scala-2.10/template-scala-parallel-universal-recommendation-assembly-0.5.0-deps.jar,file:/root/ur/target/scala-2.10/template-scala-parallel-universal-recommendation_2.10-0.5.0.jar --files file:/PredictionIO-0.10.0-incubating/conf/log4j.properties,file:/PredictionIO-0.10.0-incubating/vendors/hbase-1.0.0/conf/hbase-site.xml --driver-class-path /PredictionIO-0.10.0-incubating/conf:/PredictionIO-0.10.0-incubating/vendors/hbase-1.0.0/conf file:/PredictionIO-0.10.0-incubating/lib/pio-assembly-0.10.0-incubating.jar --engine-id GwjbffjU4mg4sZHjkUMyS1fJBHQx4CVQ --engine-version 08f9b7206d6c4c46c26e6aa45fd73ed15e7de602 --engine-variant file:/root/ur/engine.json --verbosity 0 --json-extractor Both --env PIO_STORAGE_SOURCES_HBASE_TYPE=hbase,PIO_ENV_LOADED=1,PIO_STORAGE_REPOSITORIES_METADATA_NAME=pio_meta,PIO_VERSION=0.10.0,PIO_FS_BASEDIR=/root/.pio_store,PIO_STORAGE_SOURCES_ELASTICSEARCH_HOSTS=localhost,PIO_STORAGE_SOURCES_HBASE_HOME=/PredictionIO-0.10.0-incubating/vendors/hbase-1.0.0,PIO_HOME=/PredictionIO-0.10.0-incubating,PIO_FS_ENGINESDIR=/root/.pio_store/engines,PIO_STORAGE_SOURCES_LOCALFS_PATH=/root/.pio_store/models,PIO_STORAGE_SOURCES_ELASTICSEARCH_TYPE=elasticsearch,PIO_STORAGE_REPOSITORIES_METADATA_SOURCE=ELASTICSEARCH,PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE=LOCALFS,PIO_STORAGE_REPOSITORIES_EVENTDATA_NAME=pio_event,PIO_STORAGE_SOURCES_ELASTICSEARCH_CLUSTERNAME=predictionio,PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME=/PredictionIO-0.10.0-incubating/vendors/elasticsearch-1.4.4,PIO_FS_TMPDIR=/root/.pio_store/tmp,PIO_STORAGE_REPOSITORIES_MODELDATA_NAME=pio_model,PIO_STORAGE_REPOSITORIES_EVENTDATA_SOURCE=HBASE,PIO_CONF_DIR=/PredictionIO-0.10.0-incubating/conf,PIO_STORAGE_SOURCES_ELASTICSEARCH_PORTS=9300,PIO_STORAGE_SOURCES_LOCALFS_TYPE=localfs
[INFO] [RecommendationEngine$]

               _   _             __  __ _
     /\       | | (_)           |  \/  | |
    /  \   ___| |_ _  ___  _ __ | \  / | |
   / /\ \ / __| __| |/ _ \| '_ \| |\/| | |
  / ____ \ (__| |_| | (_) | | | | |  | | |____
 /_/    \_\___|\__|_|\___/|_| |_|_|  |_|______|



[INFO] [Engine] Extracting datasource params...
[INFO] [WorkflowUtils$] No 'name' is found. Default empty String will be used.
[INFO] [Engine] Datasource params: (,DataSourceParams(handmade,List(purchase, view),None))
[INFO] [Engine] Extracting preparator params...
[INFO] [Engine] Preparator params: (,Empty)
[INFO] [Engine] Extracting serving params...
[INFO] [Engine] Serving params: (,Empty)
[INFO] [Remoting] Starting remoting
[INFO] [Remoting] Remoting started; listening on addresses :[akka.tcp://sparkDriver@172.17.0.2:39501]
[WARN] [MetricsSystem] Using default name DAGScheduler for source because spark.app.id is not set.
[INFO] [DataSource]
??????????????????????????????????????????????????????????????
? Init DataSource                                            ?
? ?????????????????????????????????????????????????????????? ?
? App name                      handmade                     ?
? Event window                  None                         ?
? Event names                   List(purchase, view)         ?
??????????????????????????????????????????????????????????????

[INFO] [URAlgorithm]
??????????????????????????????????????????????????????????????
? Init URAlgorithm                                           ?
? ?????????????????????????????????????????????????????????? ?
? App name                      handmade                     ?
? ES index name                 urindex                      ?
? ES type name                  items                        ?
? RecsModel                     all                          ?
? Event names                   List(purchase, view)         ?
? ?????????????????????????????????????????????????????????? ?
? Random seed                   1517559198                   ?
? MaxCorrelatorsPerEventType    50                           ?
? MaxEventsPerEventType         500                          ?
? ?????????????????????????????????????????????????????????? ?
? User bias                     1.0                          ?
? Item bias                     1.0                          ?
? Max query events              100                          ?
? Limit                         4                            ?
? ?????????????????????????????????????????????????????????? ?
? Rankings:                                                  ?
? popular                       Some(popRank)                ?
??????????????????????????????????????????????????????????????

[INFO] [Engine$] EngineWorkflow.train
[INFO] [Engine$] DataSource: org.template.DataSource@447521e
[INFO] [Engine$] Preparator: org.template.Preparator@458031da
[INFO] [Engine$] AlgorithmList: List(org.template.URAlgorithm@463045fb)
[INFO] [Engine$] Data sanity check is on.
[WARN] [TableInputFormatBase] Cannot resolve the host name for 5299d63cee83/172.17.0.2 because of javax.naming.NameNotFoundException: DNS name not found [response code 3]; remaining name '2.0.17.172.in-addr.arpa'
[INFO] [DataSource] Received events List(purchase, view)
[INFO] [DataSource] Number of events List(8, 4)
[WARN] [TableInputFormatBase] Cannot resolve the host name for 5299d63cee83/172.17.0.2 because of javax.naming.NameNotFoundException: DNS name not found [response code 3]; remaining name '2.0.17.172.in-addr.arpa'
[INFO] [Engine$] org.template.TrainingData does not support data sanity check. Skipping check.
```

`pio deploy`

returns:
```
[ERROR] [Console$] No valid engine instance found for engine GwjbffjU4mg4sZHjkUMyS1fJBHQx4CVQ 08f9b7206d6c4c46c26e6aa45fd73ed15e7de602.
Try running 'train' before 'deploy'. Aborting.
```

**Comment by pferrel** [comment]
You must run `./examples/integration-test` from within the UR directory, could this be the problem? Also you should not be running anything as “root".

Also please use the Google Group for questions. https://groups.google.com/forum/#!forum/actionml-user <https://groups.google.com/forum/#!forum/actionml-user>
 

On Apr 11, 2017, at 5:04 AM, Kamil Badyla <notifications@github.com> wrote:

Integration test doesn't work for me and it doesn't return any error whatsoever. I found that the problem is in model training

When trying to train recommender using command:

pio train -- --driver-memory 4g --executor-memory 4g

it returns

[INFO] [Console$] Using existing engine manifest JSON at /root/ur/manifest.json
[INFO] [Runner$] Submission command: /PredictionIO-0.10.0-incubating/vendors/spark-1.5.1-bin-hadoop2.6/bin/spark-submit --driver-memory 4g --executor-memory 4g --class org.apache.predictionio.workflow.CreateWorkflow --jars file:/root/ur/target/scala-2.10/template-scala-parallel-universal-recommendation-assembly-0.5.0-deps.jar,file:/root/ur/target/scala-2.10/template-scala-parallel-universal-recommendation_2.10-0.5.0.jar --files file:/PredictionIO-0.10.0-incubating/conf/log4j.properties,file:/PredictionIO-0.10.0-incubating/vendors/hbase-1.0.0/conf/hbase-site.xml --driver-class-path /PredictionIO-0.10.0-incubating/conf:/PredictionIO-0.10.0-incubating/vendors/hbase-1.0.0/conf file:/PredictionIO-0.10.0-incubating/lib/pio-assembly-0.10.0-incubating.jar --engine-id GwjbffjU4mg4sZHjkUMyS1fJBHQx4CVQ --engine-version 08f9b7206d6c4c46c26e6aa45fd73ed15e7de602 --engine-variant file:/root/ur/engine.json --verbosity 0 --json-extractor Both --env PIO_STORAGE_SOURCES_HBASE_TYPE=hbase,PIO_ENV_LOADED=1,PIO_STORAGE_REPOSITORIES_METADATA_NAME=pio_meta,PIO_VERSION=0.10.0,PIO_FS_BASEDIR=/root/.pio_store,PIO_STORAGE_SOURCES_ELASTICSEARCH_HOSTS=localhost,PIO_STORAGE_SOURCES_HBASE_HOME=/PredictionIO-0.10.0-incubating/vendors/hbase-1.0.0,PIO_HOME=/PredictionIO-0.10.0-incubating,PIO_FS_ENGINESDIR=/root/.pio_store/engines,PIO_STORAGE_SOURCES_LOCALFS_PATH=/root/.pio_store/models,PIO_STORAGE_SOURCES_ELASTICSEARCH_TYPE=elasticsearch,PIO_STORAGE_REPOSITORIES_METADATA_SOURCE=ELASTICSEARCH,PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE=LOCALFS,PIO_STORAGE_REPOSITORIES_EVENTDATA_NAME=pio_event,PIO_STORAGE_SOURCES_ELASTICSEARCH_CLUSTERNAME=predictionio,PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME=/PredictionIO-0.10.0-incubating/vendors/elasticsearch-1.4.4,PIO_FS_TMPDIR=/root/.pio_store/tmp,PIO_STORAGE_REPOSITORIES_MODELDATA_NAME=pio_model,PIO_STORAGE_REPOSITORIES_EVENTDATA_SOURCE=HBASE,PIO_CONF_DIR=/PredictionIO-0.10.0-incubating/conf,PIO_STORAGE_SOURCES_ELASTICSEARCH_PORTS=9300,PIO_STORAGE_SOURCES_LOCALFS_TYPE=localfs
[INFO] [RecommendationEngine$]

               _   _             __  __ _
     /\       | | (_)           |  \/  | |
    /  \   ___| |_ _  ___  _ __ | \  / | |
   / /\ \ / __| __| |/ _ \| '_ \| |\/| | |
  / ____ \ (__| |_| | (_) | | | | |  | | |____
 /_/    \_\___|\__|_|\___/|_| |_|_|  |_|______|



[INFO] [Engine] Extracting datasource params...
[INFO] [WorkflowUtils$] No 'name' is found. Default empty String will be used.
[INFO] [Engine] Datasource params: (,DataSourceParams(handmade,List(purchase, view),None))
[INFO] [Engine] Extracting preparator params...
[INFO] [Engine] Preparator params: (,Empty)
[INFO] [Engine] Extracting serving params...
[INFO] [Engine] Serving params: (,Empty)
[INFO] [Remoting] Starting remoting
[INFO] [Remoting] Remoting started; listening on addresses :[akka.tcp://sparkDriver@172.17.0.2:39501]
[WARN] [MetricsSystem] Using default name DAGScheduler for source because spark.app.id is not set.
[INFO] [DataSource]
??????????????????????????????????????????????????????????????
? Init DataSource                                            ?
? ?????????????????????????????????????????????????????????? ?
? App name                      handmade                     ?
? Event window                  None                         ?
? Event names                   List(purchase, view)         ?
??????????????????????????????????????????????????????????????

[INFO] [URAlgorithm]
??????????????????????????????????????????????????????????????
? Init URAlgorithm                                           ?
? ?????????????????????????????????????????????????????????? ?
? App name                      handmade                     ?
? ES index name                 urindex                      ?
? ES type name                  items                        ?
? RecsModel                     all                          ?
? Event names                   List(purchase, view)         ?
? ?????????????????????????????????????????????????????????? ?
? Random seed                   1517559198                   ?
? MaxCorrelatorsPerEventType    50                           ?
? MaxEventsPerEventType         500                          ?
? ?????????????????????????????????????????????????????????? ?
? User bias                     1.0                          ?
? Item bias                     1.0                          ?
? Max query events              100                          ?
? Limit                         4                            ?
? ?????????????????????????????????????????????????????????? ?
? Rankings:                                                  ?
? popular                       Some(popRank)                ?
??????????????????????????????????????????????????????????????

[INFO] [Engine$] EngineWorkflow.train
[INFO] [Engine$] DataSource: org.template.DataSource@447521e
[INFO] [Engine$] Preparator: org.template.Preparator@458031da
[INFO] [Engine$] AlgorithmList: List(org.template.URAlgorithm@463045fb)
[INFO] [Engine$] Data sanity check is on.
[WARN] [TableInputFormatBase] Cannot resolve the host name for 5299d63cee83/172.17.0.2 because of javax.naming.NameNotFoundException: DNS name not found [response code 3]; weeremaining name '2.0.17.172.in-addr.arpa'
[INFO] [DataSource] Received events List(purchase, view)
[INFO] [DataSource] Number of events List(8, 4)
[WARN] [TableInputFormatBase] Cannot resolve the host name for 5299d63cee83/172.17.0.2 because of javax.naming.NameNotFoundException: DNS name not found [response code 3]; remaining name '2.0.17.172.in-addr.arpa'
[INFO] [Engine$] org.template.TrainingData does not support data sanity check. Skipping check.
pio deploy

returns:

[ERROR] [Console$] No valid engine instance found for engine GwjbffjU4mg4sZHjkUMyS1fJBHQx4CVQ 08f9b7206d6c4c46c26e6aa45fd73ed15e7de602.
Try running 'train' before 'deploy'. Aborting.

**Comment by badeleux** [comment]
I do run it from within ur directory.
I run it in docker container which by default logs me as root. Don't think it could be a problem.

**Comment by pferrel** [comment]
There are no supported containers for PIO + UR, we support many other configs and use containers for the component services but sionce I have not idea how this container was setup, you are a bit on your own.

Can you share the entire output of ./examples/integration-test ? There may be some clues there and please use the Google group for discussions.


On Apr 11, 2017, at 11:49 AM, Kamil Badyla <notifications@github.com> wrote:

I do run it from within ur directory.
I run it in docker container which by default logs me as root. Don't think it could be a problem.

**Comment by pferrel** [comment]
discussion should go to the google group, this is for bugs or enhancements only

**Comment by pferrel** [comment]
Hi
I have exactly the same problem, I am also running it in docker. 
Unfortunately pio train finishes to run successfully, but pio deploy fails 
with :

No valid engine instance found for engine com.actionml.RecommendationEngine 
4dff8bf8784079cc90ba9df7dd5c243d41c34293.
Try running 'train' before 'deploy'. Aborting.
