### ISSUE TITLE
0.12.0-incubating support

### ISSUE THREAD

**Issue by Arnold-Ampp** [actionml/universal-recommender#41]
Does anyone have this engine working with PredictionIO-0.12.0-incubating? 

or should I just stick to 0.11.0?

**Comment by pferrel** [comment]
Working on it now, we will upgrade several of the required services too like Elasticsearch to 5.5.x

This requires use to use the REST client instead of the TransportClient for ES and so is a decent amount of work. There is a PR for some of the work so I expect this to be ready to test next week.

BTW better response if you ask on the Google Group: https://groups.google.com/forum/#!forum/actionml-user

**Comment by arnold-almeida** [comment]
Thanks for the info @pferrel 👍
